kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-node-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 40Gi
  local:
    path: /data/postgres
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - #CHANGE_HOST#
